### ISSUE TITLE
Can CDS service discovery flex based upon the capabilities of the EHR?

### ISSUE THREAD

**Issue by olbrich** [cds-hooks/docs#15]
When it comes to service discovery, it may make sense for the CDS service discovery endpoint to interrogate the CapabilityStatement of the EHR that is attempting service discovery.

This would allow a service discovery endpoint to be able to determine if the EHR in question supports the necessary FHIR resources and is of an appropriate version to successfully interact with the CDS service and filter out responses as necessary.

This might require calls to `/cds-services` to include an `iss` parameter.

**Comment by Penumbra69** [comment]
You're proposing a negotiated 2-way capability handshake?  

As I understood it, discovery is really one way: Designed for the configured EHR to discover what Hooks / capabilities the services URL have available (allowing the endpoint server / service to be modified/added to without impacting the EHR at all.)

You are saying you'd like that to go both ways?  

I just wonder, given the current implementation design flow, how a URL for a CDS-Hook server got into the EHR without the EHR being able to support it.  If we were talking about placing a CDS-Hook URL in a centralized "discovery" server that the EHR had never seen/used/been configured for -this makes sense.

Do you have a specific use case in mind?

**Comment by olbrich** [comment]
As a provider of CDS services, it makes sense for me to have a url that describes all of my services.  Multiple integration partners would want to interrogate the same url and each should only get back a list of services that are compatible with their EHR.  

This also allows me to take a progressive enhancement approach.  For example.. if I have an integration partner that is in the process of implementing several FHIR resources, I won't advertise a service to them until they have implemented the capabilities that are required to successfully use the tool.

**Comment by Penumbra69** [comment]
Help me - what am I missing here?

From my perspective - If an EHR can't consume a hook because it hasn't been configured to do so - it therefore wouldn't call the hook it doesn't recognize, right? 

My spitball thought experiment:

If 3 servers A, B, C called the same hooks service endpoint (call it Q) with hooks 1, 2, 3, 4, 5.

Let A recognize hooks 1, 2
Let B recognize hooks 1, 3
Let C recognize hooks 4, 5

How would A be troubled by 3, 4, 5 - similarly B with 2, 4, 5 and C with 1, 2, 3?

They wouldn't recognize the hooks they didn't configure, and just wouldn't call on the service for them - right? Are you concerned that they would, and in turn break because they weren't prepared?

**Comment by kpshek** [comment]
@olbrich - My apologies for not commenting on this issue much earlier.

I agree with you in that CDS services (when possible), should utilize a progressive enhancement approach to their functionality. That is, the CDS service makes every attempt to work with the FHIR capabilities of each EHR.

We've been working under the assumption that the EHR is solely responsible for determining which CDS services they consume or integrate with. This includes likely offline coordination between the CDS service provider and EHR. I see your viewpoint though that in order to remove manual coordination, the CDS service would need to be able to advertise the FHIR resources it requires.

One way to do this would be to pass the `iss` parameter in the Discovery request to the CDS service (`/cds-services`) like you suggested. The complication here is that some EHRs will support multiple FHIR versions so the EHR would need to call Discovery for each FHIR version they support.

Another way to do this would be for the CDS service to list the FHIR resources it needs in the Discovery response. However, this provides a more coarse grained view and doesn't get into the specific fields that the CDS service may require on each FHIR resource.

Taking a step back, we have this exact same concern today with SMART on FHIR. That is, EHRs have no way of knowing if a given SMART app will work based on the current FHIR capabilities of the EHR. However, this hasn't been an issue due to the aforementioned offline coordination between the EHR and SMART application. Barring this offline coordination, the SMART app needs to either utilize a progressive enhancement approach (as you mentioned) or communicate to the user that it requires data which isn't available. I think the same is true for CDS services.

My thoughts are that we don't make any changes for the time being regarding this for the following reasons:
- We're relying on that offline coordination -- both within CDS Hooks and SMART on FHIR
- CDS services should utilize a progressive enhancement approach. If required data is not available, it can communicate that to the user via a card (this also may relate to our errors discussion in #14)

**Comment by seanmsmith23** [comment]
The idea of having some communication back and forth about the minimum FHIR resources required definitely has some appeal, but given the complications @kpshek outlines above (differing version support, what if you need specific fields on a specific resource, etc..) I'd say leaving this to an offline process feels right to me.

In practice (as a CDS-service), we would probably put some logic into our Discovery endpoint that can quickly enable/disable services for different clients. Then during our discussions with the client team about getting our CDS-service online we'd naturally be having a conversation about what FHIR resources they support - if the minimum requirements weren't met, we'd go in and disable the service for that client until a future time. That doesn't feel unduly arduous to me.

Maybe this can be revisited further down the line if it's causing big headaches, but in the interest of not making the standard more confusing or challenging to implement I'd vote for staying with a manual/offline process.

**Comment by kpshek** [comment]
At the Madrid Connectathon this past weekend (2017-05-07), a large group of us participating in the CDS Hooks track discussed this issue in an offline discussion. This group of ~12 represented a broad set of stakeholders, from multiple EHR vendors, several CDS Service providers, and a healthcare organization. What follows is the summary of our discussion and the consensus of the group.

It was noted that the `iss` value (FHIR base URL) wouldn't satisfy all scenarios for the issue noted here. For instance, imagine a CDS Service that specifies and `Observation` prefetch query which would completely satisfy the needs/logic of this service. Now, imagine an EHR which does not support the `Observation` resource in its FHIR server but **does** support prefetching this data via some proprietary means. If the Discovery endpoint solely based it's decision on the capabilities of the FHIR server, it would mistakenly think this EHR could not call this CDS Service.

We all agreed that we want to move in the direction of streamlining and automating the integration between EHRs and CDS Services to further minimize offline work around integration. However, the group recognized that our current landscape is not here yet and until that time, it does not make any changes around this.

**Comment by kpshek** [comment]
Closing this issue as deferred per the discussion amongst the broad stakeholders at the Madrid Connectathon back in May.
