### ISSUE TITLE
Clarification on out-of-band key discovery

### ISSUE THREAD

**Issue by yashaskram** [cds-hooks/docs#361]
>The EHR MAY make its JWK Set available via a URL identified by the jku header field, as defined by rfc7515 4.1.2. If the jku header field is ommitted, the EHR and CDS Service SHALL communicate the JWK Set out-of-band.

- Does out-of-band cover both sharing jwks_uri  (jku) and jwk? 
- If latter is allowed, should kid should be optional similar to jku or still be required?

**Comment by kpshek** [comment]
@yashaskram - 

> Does out-of-band cover both sharing jwks_uri (jku) and jwk?

Presumably if the CDS Client shares the JWK Set containing the public key(s) out-of-band, there is no `jku` value to specify since the JWK Set isn't available at a public URL endpoint.

> If latter is allowed, should kid should be optional similar to jku or still be required?

`kid` should still be required if a the JWK Set is shared out-of-bound because that JWK Set can still contain multiple public keys. In this case, the `kid` is necessary to identify the appropriate public key to use to verify the signature on a JWT.

Closing as question answer.
