### ISSUE TITLE
FHIR Data Types

### ISSUE THREAD

**Issue by brettmarquard** [cds-hooks/docs#516]
During review of PR #513 and PR #505 the team discussed using the FHIR codeableConcept data type rather than writing out guidance in **OverrideReason** and **Topic**.  Consider adding a note in the CDS hooks spec on the reason for not using FHIR Data Types.

**Comment by dennispatterson** [comment]
I wasn't involved back then, but I know in the past there was some heavier usage of FHIR in the API.  One example was using the Parameters resource, but ultimately it was abandoned for being too verbose.

The 1.0 spec uses the `application/json` media type.  That being the case, all API definitions use json data types.  FHIR data types aren't on the table since they belong to `application/fhir+json`.  Switching to that would mean all data elements would presumably need to use FHIR data types.  We kind of get around CDS Hooks being json but _using_ FHIR by indicating that something is a json `object` and in the description mentioning that it's FHIR (e.g. prefetch, order-select's draftOrders).

The emerging use-cases Brett mentions seem to be codified, so there's natural thoughts of codified data in FHIR.  Short of coming up with a different strategy for those fields, we're looking at either listing out the code/system/label fields discretely as json fields, or saying that those too are `objects`/`arrays`  but describe their contents as Codings.

**Comment by dennispatterson** [comment]
Additional discussion for this out on Zulip - https://chat.fhir.org/#narrow/stream/179159-cds-hooks/topic/Coding.20data.20type
