### ISSUE TITLE
Support for non-FHIR clinical models

### ISSUE THREAD

**Issue by rongchen** [cds-hooks/docs#78]
We build cds-services for local EMR/GP systems in Nordic market, and are very interested in the cds-hooks design. However given FHIR adoption rate for real-use is currently very low here in this part of the world, having cds-hooks hard-wired to FHIR resources would significantly increase the barrier for its use.

From a design point of view, cds-hooks can work equally well with other standardized non-FHIR clinical models such as openEHR archetypes, CIMI and EN13606. Is there any plan to allow such extension in the future?

**Comment by bdoolittle** [comment]
At its heart, CDS-Hooks is a standard for the event-based invocation of remote services. It does not need to be tightly coupled to any single data model, but I imagine that there would be a tradeoff between the number of data models supported by CDS-Hooks and the interoperability it grants. In the short term, it's important to not over complicate the standard so that the 1.0 version can get off the ground. In the long run, decoupling CDS-Hooks from it's underlying data model seems generally like a good idea as standards always change.

You should not feel limited by CDS-Hooks being hard-wired to FHIR. The standard can be extended to use a different data model, it just requires an integration between CDS Provider and EHR.

**Comment by rongchen** [comment]
Well said.

**Comment by grahamegrieve** [comment]
given that cds-hooks is open, the likely thing to do is to fork the source, adapt it to openEHR, and see how close you can keep to the original. Then you'll have a solid base for bringing change proposals to the spec

**Comment by rongchen** [comment]
@grahamegrieve very good idea indeed. In fact, we really want to make CDS-Hooks work for openEHR as well as other standards or non-standards based EHRs.

**Comment by isaacvetter** [comment]
@rongchen - it sounds like you got an answer that made you happy - closing.
@bdoolittle - I think that #76 better captures your concern, and note that it's also marked as 1.0. Closing.
