### ISSUE TITLE
Decisions without interaction

### ISSUE THREAD

**Issue by robs16** [cds-hooks/docs#85]
There are cases where the CDS service may send back a decision without interaction with the user. For example, the request may have resulted in no cards because no interaction with the clinician was necessary, but the order must be updated with a rating. The specification does not prevent this, but nor does it recognize it as a valid workflow. As a result, EMRs might deny this type of processing. This scenario should be added to the documentation to make it clear that EMRs must support this type of processing.

**Comment by bdoolittle** [comment]
@robs16, how does your described use case for decisions relate to issue [__#48__](https://github.com/cds-hooks/docs/issues/48)?

**Comment by robs16** [comment]
The solution here would be to update the order with the rating via the #48 approach as implemented in #64  (FHIR extensions applied to the FHIR resource).

**Comment by kpshek** [comment]
Thanks for the feedback @robs16.

As you're aware (since you were present for the discussion), the community reached consensus at the Sept 2017 San Diego Connectathon to remove decisions for the 1.0 release (#99) until we obtain more implementer feedback. We will swing back on the decisions feature on a subsequent release. As such, I'm closing this issue with a _deferred_ label.
