### ISSUE TITLE
Decisions need an update

### ISSUE THREAD

**Issue by robs16** [cds-hooks/docs#86]
Decisions should include an 'update' array to match the suggestion action types. Currently only create and delete are provided.

**Comment by bdoolittle** [comment]
I agree, the decision and suggestion structures should be consistent.

**Comment by rongchen** [comment]
This seems to be an obvious inconsistency. Will it be fixed in v1.0?

**Comment by kpshek** [comment]
Thanks for the feedback @robs16.

As you're aware (since you were present for the discussion), the community reached consensus at the Sept 2017 San Diego Connectathon to remove decisions for the 1.0 release (#99) until we obtain more implementer feedback. We will swing back on the decisions feature on a subsequent release. As such, I'm closing this issue with a _deferred_ label.
